[platformio]
default_envs = test_webserver

[env]
platform = espressif32
board = esp32cam
framework = arduino

upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
upload_speed = 460800

monitor_rts = 0
monitor_dtr = 0

board_build.partitions = min_spiffs.csv
board_build.f_cpu = 160000000L

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=2

lib_deps =
    https://github.com/tzapu/WiFiManager.git

[env:test_webserver]
build_src_filter =
    -<*>
    +<shared/*.cpp>
    +<test_webserver/*.cpp>

[env:pic_sender]
build_src_filter =
    -<*>
    +<shared/*.cpp>
    +<pic_sender/*.cpp>
